# Generated by Django 5.2.6 on 2025-09-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_order_guest_email_order_guest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
